namespace Core.DTOs
{
    /// <summary>
    /// DTO for Kadam Programme Report - matches Report Format Excel columns
    /// </summary>
    public class KadamProgrammeReportDTO
    {
        public int SrNo { get; set; }
        public string? CreatedBy { get; set; }
        public string? UserId { get; set; }
        public string? State { get; set; }
        public string? Division { get; set; }
        public string? District { get; set; }
        public string? Block { get; set; }
        public string? Village { get; set; }
        public string? TypeOfInstitution { get; set; }
        public string? InstitutionBuilding { get; set; }
        public string? InstitutionName { get; set; }
        public string? InstitutionDISECode { get; set; }
        public string? TeachersName { get; set; }
        public string? StudentsKadamId { get; set; }
        public string? StudentsFirstName { get; set; }
        public string? StudentsLastName { get; set; }
        public string? StudentsDateOfBirth { get; set; }
        public string? StudentsAge { get; set; }
        public string? StudentsGender { get; set; }
        public string? DoYouHaveAadhaarCard { get; set; }
        public string? StudentAadharNo { get; set; }
        public string? FathersName { get; set; }
        public string? FathersAge { get; set; }
        public string? FathersOccupation { get; set; }
        public string? FathersEducation { get; set; }
        public string? MothersName { get; set; }
        public string? MothersAge { get; set; }
        public string? MothersOccupation { get; set; }
        public string? MothersEducation { get; set; }
        public string? EnrolmentDate { get; set; }
        public string? EnrolmentGrade { get; set; }
        public string? Section { get; set; }
        public string? CurrentGrade { get; set; }
        public string? CurrentSection { get; set; }
        public string? PromotionDate { get; set; }
        public string? StudentsSRGivenByInstitution { get; set; }
        public string? SchoolingStatus { get; set; }
        public string? DroppedOutClass { get; set; }
        public string? DroppedOutYear { get; set; }
        public string? Reasons { get; set; }
        public string? HowLongPlanningToStay { get; set; }
        public string? ContactNo { get; set; }
        public string? AlternateContactNumber { get; set; }
        public string? HouseAddress { get; set; }
        public string? Pincode { get; set; }
        public string? PeopleLivingInHouse { get; set; }
        public string? Cast { get; set; }
        public string? Religion { get; set; }
        public string? ParentsMonthlyIncome { get; set; }
        public string? ParentsMonthlyExpenditure { get; set; }
        public string? IsChildPhysicallyChallenged { get; set; }
        public string? PhysicallyChallengedType { get; set; }
        public string? PhysicallyChallengedPercent { get; set; }
        public string? DisabilityCertificateAvailable { get; set; }
        public string? TypeOfDocument { get; set; }
        public string? DocumentNumber { get; set; }
        public string? DocumentAvailable { get; set; }
        public string? TrioNo { get; set; }
        public string? BaselineMath { get; set; }
        public string? BaselineEnglish { get; set; }
        public string? BaselineEVS { get; set; }
        public string? BaselineHindi { get; set; }
        public string? BaselineTotal { get; set; }
        public string? BaselinePercentage { get; set; }
        public string? BaselineDate { get; set; }
        public string? EntryLevelStep { get; set; }
        public string? ExitLevelStep { get; set; }
        public string? OngoingStep { get; set; }
        public string? NoOfStepsCompleted { get; set; }
        public string? GradeTest1 { get; set; }
        public string? GradeTest2 { get; set; }
        public string? GradeTest3 { get; set; }
        public string? GradeTest4 { get; set; }
        public string? GradeTest5 { get; set; }
        public string? ProgressSpeed { get; set; }
        public string? ProgressColor { get; set; }
        public string? MonthsRequiredToReachAgeAppropriateLevel { get; set; }
        public string? NoOfSchoolUniformReceived { get; set; }
        public string? SchoolUniformReceivedDate { get; set; }
        public string? NoOfStationeryKitReceived { get; set; }
        public string? StationeryKitReceivedLastDate { get; set; }
        public string? AttendancePercent { get; set; }
        public string? MidDayMealPercent { get; set; }
        public string? StudentsStatus { get; set; }
        public string? EndlineMath { get; set; }
        public string? EndlineEnglish { get; set; }
        public string? EndlineEVS { get; set; }
        public string? EndlineHindi { get; set; }
        public string? EndlineTotal { get; set; }
        public string? EndlinePercentage { get; set; }
        public string? EndlineDate { get; set; }
        public string? IsMainstreamInstitutionSame { get; set; }
        public string? MainstreamInstitutionName { get; set; }
        public string? SchoolDISECode { get; set; }
        public string? MainstreamGrade { get; set; }
        public string? MainstreamSection { get; set; }
        public string? ChildSRGivenByInstitution { get; set; }
        public string? MainstreamDate { get; set; }
        public string? CurrentGradeAfterMainstream { get; set; }
        public string? InactiveDate { get; set; }
        public string? InactiveReasons { get; set; }
        public string? InactiveRemarks { get; set; }
        public string? BroughtBackDate { get; set; }
        public string? BroughtBackReason { get; set; }
        public string? LastDateOfInactiveFollowUp { get; set; }
        public string? ResponseToPhoneCall { get; set; }
        public string? EnrolledInSchool { get; set; }
        public string? SchoolName { get; set; }
        public string? EnrolmentGradeInactiveFollowUp { get; set; }
        public string? CurrentAddressState { get; set; }
        public string? StatusAfterMainstream { get; set; }
        public string? StudentAttendanceToday { get; set; }
        public string? StudentAttendancePercentLastMonth { get; set; }
        public string? LastExamPercent { get; set; }
    }
}
