IF OBJECT_ID('dbo.InstitutionImportStaging', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.InstitutionImportStaging
    (
        Id BIGINT IDENTITY(1,1) PRIMARY KEY,
        ImportId UNIQUEIDENTIFIER NOT NULL,
        RowNumber INT NOT NULL,
        DivisionName NVARCHAR(100) COLLATE DATABASE_DEFAULT NOT NULL DEFAULT '',
        StateName NVARCHAR(100) COLLATE DATABASE_DEFAULT NOT NULL DEFAULT '',
        DistrictName NVARCHAR(100) COLLATE DATABASE_DEFAULT NOT NULL DEFAULT '',
        BlockName NVARCHAR(100) COLLATE DATABASE_DEFAULT NOT NULL DEFAULT '',
        VillageName NVARCHAR(100) COLLATE DATABASE_DEFAULT NOT NULL DEFAULT '',
        InstitutionTypeName NVARCHAR(100) COLLATE DATABASE_DEFAULT NOT NULL DEFAULT '',
        InstitutionBuildingName NVARCHAR(100) COLLATE DATABASE_DEFAULT NOT NULL DEFAULT '',
        InstitutionName NVARCHAR(100) COLLATE DATABASE_DEFAULT NOT NULL DEFAULT '',
        InstitutionCode NVARCHAR(100) COLLATE DATABASE_DEFAULT NOT NULL DEFAULT '',
        InstitutionBusinessId NVARCHAR(100) COLLATE DATABASE_DEFAULT NOT NULL DEFAULT '',
        InstitutionHeadMasterName NVARCHAR(100) COLLATE DATABASE_DEFAULT NOT NULL DEFAULT '',
        InstitutionPhone NVARCHAR(25) COLLATE DATABASE_DEFAULT NOT NULL DEFAULT '',
        MaleTeachers NVARCHAR(20) COLLATE DATABASE_DEFAULT NOT NULL DEFAULT '',
        FemaleTeachers NVARCHAR(20) COLLATE DATABASE_DEFAULT NOT NULL DEFAULT '',
        TotalStudents NVARCHAR(20) COLLATE DATABASE_DEFAULT NOT NULL DEFAULT '',
        FinancialYearStart NVARCHAR(25) COLLATE DATABASE_DEFAULT NOT NULL DEFAULT '',
        FinancialYearEnd NVARCHAR(25) COLLATE DATABASE_DEFAULT NOT NULL DEFAULT '',
        GradeSections NVARCHAR(1000) COLLATE DATABASE_DEFAULT NOT NULL DEFAULT '',
        DivisionId INT NULL,
        StateId INT NULL,
        DistrictId INT NULL,
        BlockId INT NULL,
        VillageId INT NULL,
        InstitutionType INT NULL,
        InstitutionBuilding INT NULL,
        CreatedAt DATETIME NOT NULL DEFAULT GETDATE()
    );

    CREATE NONCLUSTERED INDEX IX_InstitutionImportStaging_ImportId
        ON dbo.InstitutionImportStaging (ImportId)
        INCLUDE (RowNumber);
END;
GO

-- Align collation on existing staging tables (live servers created before this fix).
IF OBJECT_ID('dbo.InstitutionImportStaging', 'U') IS NOT NULL
BEGIN
    ALTER TABLE dbo.InstitutionImportStaging ALTER COLUMN DivisionName NVARCHAR(100) COLLATE DATABASE_DEFAULT NOT NULL;
    ALTER TABLE dbo.InstitutionImportStaging ALTER COLUMN StateName NVARCHAR(100) COLLATE DATABASE_DEFAULT NOT NULL;
    ALTER TABLE dbo.InstitutionImportStaging ALTER COLUMN DistrictName NVARCHAR(100) COLLATE DATABASE_DEFAULT NOT NULL;
    ALTER TABLE dbo.InstitutionImportStaging ALTER COLUMN BlockName NVARCHAR(100) COLLATE DATABASE_DEFAULT NOT NULL;
    ALTER TABLE dbo.InstitutionImportStaging ALTER COLUMN VillageName NVARCHAR(100) COLLATE DATABASE_DEFAULT NOT NULL;
    ALTER TABLE dbo.InstitutionImportStaging ALTER COLUMN InstitutionTypeName NVARCHAR(100) COLLATE DATABASE_DEFAULT NOT NULL;
    ALTER TABLE dbo.InstitutionImportStaging ALTER COLUMN InstitutionBuildingName NVARCHAR(100) COLLATE DATABASE_DEFAULT NOT NULL;
    ALTER TABLE dbo.InstitutionImportStaging ALTER COLUMN InstitutionName NVARCHAR(100) COLLATE DATABASE_DEFAULT NOT NULL;
    ALTER TABLE dbo.InstitutionImportStaging ALTER COLUMN InstitutionCode NVARCHAR(100) COLLATE DATABASE_DEFAULT NOT NULL;
    ALTER TABLE dbo.InstitutionImportStaging ALTER COLUMN InstitutionBusinessId NVARCHAR(100) COLLATE DATABASE_DEFAULT NOT NULL;
    ALTER TABLE dbo.InstitutionImportStaging ALTER COLUMN InstitutionHeadMasterName NVARCHAR(100) COLLATE DATABASE_DEFAULT NOT NULL;
    ALTER TABLE dbo.InstitutionImportStaging ALTER COLUMN InstitutionPhone NVARCHAR(25) COLLATE DATABASE_DEFAULT NOT NULL;
    ALTER TABLE dbo.InstitutionImportStaging ALTER COLUMN MaleTeachers NVARCHAR(20) COLLATE DATABASE_DEFAULT NOT NULL;
    ALTER TABLE dbo.InstitutionImportStaging ALTER COLUMN FemaleTeachers NVARCHAR(20) COLLATE DATABASE_DEFAULT NOT NULL;
    ALTER TABLE dbo.InstitutionImportStaging ALTER COLUMN TotalStudents NVARCHAR(20) COLLATE DATABASE_DEFAULT NOT NULL;
    ALTER TABLE dbo.InstitutionImportStaging ALTER COLUMN FinancialYearStart NVARCHAR(25) COLLATE DATABASE_DEFAULT NOT NULL;
    ALTER TABLE dbo.InstitutionImportStaging ALTER COLUMN FinancialYearEnd NVARCHAR(25) COLLATE DATABASE_DEFAULT NOT NULL;
    ALTER TABLE dbo.InstitutionImportStaging ALTER COLUMN GradeSections NVARCHAR(1000) COLLATE DATABASE_DEFAULT NOT NULL;
END;
GO
