Create Table Institutions (
    Id Int Identity(1,1) Primary Key,
    DivisionId INT NOT NULL,
    StateId INT NOT NULL,
    DistrictId INT NOT NULL,
    BlockId INT NOT NULL,
    VillageId INT NOT NULL,
    InstitutionType INT NOT NULL,
    InstitutionBuilding INT NOT NULL,
    InstitutionName VARCHAR(100) NOT NULL,
    InstitutionCode VARCHAR(100) NOT NULL,
    InstitutionId VARCHAR(100) NOT NULL,
    InstitutionHeadMasterName VARCHAR(100) NOT NULL,
    InstitutionPhone VARCHAR(25) NOT NULL,
    InstitutionEmail VARCHAR(100) NOT NULL,
    InstitutionWebsite VARCHAR(155) NOT NULL,
    InstitutionLogo VARCHAR(255) NOT NULL,
    InstitutionAddress VARCHAR(255) NOT NULL,
    InstitutionMaleTeacherCount INT NOT NULL,
    InstitutionFemaleTeacherCount INT NOT NULL,
    InstitutionTotalTeacherCount INT NOT NULL,
    InstitutionTotalStudentCount INT NOT NULL,
    FinancialYearStart Varchar(25) NOT NULL,
    FinancialYearEnd Varchar(25) NOT NULL,
    CurrentStatus INT NOT NULL,
    ClosedDate DATETIME,
    ClosedReason VARCHAR(255),
    ClosedBy INT,
    CreatedBy INT,
    DateCreated DATETIME DEFAULT GETDATE(),
    ModifyBy INT,
    ModifyDate DATETIME,
    DeletedBy INT,
    DeletedDate DATETIME,
    IsDeleted BIT DEFAULT 0
);