CREATE TABLE StudentFamilyDetails (
    Id INT PRIMARY KEY IDENTITY(1,1),
    StudentId INT NOT NULL,
    FatherName VARCHAR(50),
    FatherAge INT,
    FatherOccupationId INT,
    FatherEducationId INT,
    MotherName VARCHAR(50),
    MotherAge INT,
    MotherOccupationId INT,
    MotherEducationId INT,
    PrimaryContactNumber VARCHAR(20),
    AlternateContactNumber VARCHAR(20),
    HouseAddress VARCHAR(155),
    PinCode VARCHAR(10),
    PeopleInHouseId INT,
    CasteId INT,
    ReligionId INT,
    ParentMonthlyIncome DECIMAL(18,2),
    ParentMontlyExpenditure DECIMAL(18,2),
    CurrentStatus INT NOT NULL,
    CreatedBy INT,
    DateCreated DATETIME DEFAULT GETDATE(),
    ModifyBy INT,
    ModifyDate DATETIME,
    DeletedBy INT,
    DeletedDate DATETIME,
    IsDeleted BIT DEFAULT 0

);
