CREATE TABLE StudentFollowups (
    Id INT PRIMARY KEY IDENTITY(1,1),
    StudentId INT,
    FollowupDate DATETIME NOT NULL,
    InstitutionId INT NOT NULL,
    GradeId INT NOT NULL,
    Section VARCHAR(25),
    InchargeName VARCHAR(100),
    InchargeContactNumber VARCHAR(100),
    IsChildSitTogether VARCHAR(25),
    LastMonthAttendanceCount INT,
    LastMonthWorkingDayCount INT,
    LastMonthAttendancePercentage FLOAT,
    MaleStudentCount INT,
    FemaleStudentCount INT,
    TodayStudentPresentCount INT,
    TotalStudentCount INT,
    TotalStudentPercentage FLOAT,
    CurrentStatus INT NOT NULL,
    CreatedBy INT,
    DateCreated DATETIME DEFAULT GETDATE(),
    ModifyBy INT,
    ModifyDate DATETIME,
    DeletedBy INT,
    DeletedDate DATETIME,
    IsDeleted BIT DEFAULT 0
)