CREATE TABLE Students (
    Id INT PRIMARY KEY IDENTITY(1,1),
    StudentId VARCHAR(100) NOT NULL,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    Gender VARCHAR(10) NOT NULL,
    DateOfBirth DATE NOT NULL,
    DoYouHaveAadhaarCard BIT NOT NULL,
    AadhaarCardNumber VARCHAR(16) NOT NULL,
    InstitutionId INT NOT NULL,
    SectionId INT NOT NULL,
    Grade Varchar(25),
    StudentRegistratioNumber VARCHAR(50) NOT NULL,
    ChildStatudBeforeKadamSTC TinyInt NULL,
    HowLongPlaningToStayThisArea TinyInt NULL,
    Class TinyInt NULL,
    Reasons TinyInt NULL,
    DropoutClass Varchar(25) NULL,
    DropoutYear INT,
    CurrentStatus INT NOT NULL,
    CreatedBy INT,
    DateCreated DATETIME DEFAULT GETDATE(),
    ModifyBy INT,
    ModifyDate DATETIME,
    DeletedBy INT,
    DeletedDate DATETIME,
    IsDeleted BIT DEFAULT 0
)
