CREATE TABLE Users (
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Email]				[varchar](100) NOT NULL,
	[UserName]			[varchar](100) NOT NULL,
	[PasswordHash]		[varbinary](64) NOT NULL,
	PasswordSalt		[varbinary](32) Not Null,
	[FirstName]		[varchar](50) NOT NULL,
	[LastName]		[varchar](50) NOT NULL,
	[Phone] [varchar](25) NOT NULL,
	[AlternatePhone] [varchar](25) NOT NULL,
	[Gender]		TinyInt Null,
	Grade			varchar(100) NULL,
	Section			Varchar(100) NULL,
	GradeSection	Varchar(2000) NULL,
	DivisionId		INT NUll,
	[RoleId]		[int] NOT NULL,
	ReporteeRoleId	[int] NOT NULL,
	UserStatus		TinyInt Not Null,
	ActivityType	Varchar(50) Null,
	[IsDeleted]		[bit] NOT NULL,
	[DateCreated]	[datetime] NULL,
	[CreatedBy]		[int] NULL,
	[ModifyDate]	[datetime] NULL,
	[ModifyBy]		[int] NULL,
	[DeletedDate]	[datetime] NULL,
	[DeletedBy]		[int] NULL
);